debug = true

[google]
oauth_flask_secret_key = ""
oauth_secrets = "env/oauth-secrets.sample.json"
tokens = "env/tokens.sample.json"
calendar_id = ""

[raspberry]
pigpio_addr = "localhost"
red_pin = 0
green_pin = 0
blue_pin = 0
button_pin = 0
status_pin = 0

[lifx]
mac_address = ""
ip_address = ""

[controller]
use_lifx_output = true
use_rgb_led_output = true
sleep_interval_seconds = 5
poll_interval_seconds = 0
poll_interval_minutes = 1
default_color = { red = 1, green = 0, blue = 0 }